ARG SOURCE_REPOSITORY=ghcr.io/cshum/imagor-base
ARG SOURCE_TAG=latest

FROM ${SOURCE_REPOSITORY}:${SOURCE_TAG}

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    git \
    libcfitsio-dev \
    libfftw3-dev \
    libgsf-1-dev \
    libimagequant-dev \
    libmatio-dev \
    libopenjp2-7-dev \
    libopenslide-dev \
    liborc-0.4-dev \
    libpoppler-glib-dev \
    pkg-config \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
