ARG SOURCE_REPOSITORY=ghcr.io/cshum/imagor-base
ARG SOURCE_TAG=latest

FROM ${SOURCE_REPOSITORY}:${SOURCE_TAG}

RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
		build-essential \
		ca-certificates \
		git \
		libaom-dev \
		libcfitsio-dev \
		libcgif-dev \
		libdav1d-dev \
		libdeflate-dev \
		libexif-dev \
		libfftw3-dev \
		libgsf-1-dev \
		libheif-plugin-aomenc \
		libheif-plugin-x265 \
		libimagequant-dev \
		libjpeg-turbo8-dev \
		libjxl-dev \
		liblcms2-dev \
		liblerc-dev \
		liblzma-dev \
		libmagickwand-dev \
		libmatio-dev \
		libopenexr-dev \
		libopenjp2-7-dev \
		libopenslide-dev \
		liborc-0.4-dev \
		libpango1.0-dev \
		libpng-dev \
		libpoppler-glib-dev \
		libraw-dev \
		librtmp-dev \
		librsvg2-dev \
		libspng-dev \
		libtheora-dev \
		libtiff-dev \
		libnuma-dev \
		libvorbis-dev \
		libvpx-dev \
		libwebp-dev \
		libx264-dev \
		libx265-dev \
		libxml2-dev \
		libzstd-dev \
		pkg-config \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
